# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["SimuladorMegaHair.Api/SimuladorMegaHair.Api.csproj", "SimuladorMegaHair.Api/"]
COPY ["SimuladorMegaHair.Infrastructure/SimuladorMegaHair.Infrastructure.csproj", "SimuladorMegaHair.Infrastructure/"]
COPY ["SimuladorMegaHair.Domain/SimuladorMegaHair.Domain.csproj", "SimuladorMegaHair.Domain/"]
RUN dotnet restore "SimuladorMegaHair.Api/SimuladorMegaHair.Api.csproj"

COPY . .
RUN dotnet publish "SimuladorMegaHair.Api/SimuladorMegaHair.Api.csproj" \
    -c Release \
    -o /app/publish \
    --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
EXPOSE 5185
ENV ASPNETCORE_URLS=http://+:5185
ENV ASPNETCORE_ENVIRONMENT=Development
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "SimuladorMegaHair.Api.dll"]
