// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimuladorMegaHair.Infrastructure.Data;

#nullable disable

namespace SimuladorMegaHair.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260821210253_create-ini")]
    partial class CreateIni
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimuladorMegaHair.Domain.Entities.CatalogoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutorizadoUsoImagem")
                        .HasColumnType("boolean");

                    b.Property<string>("Comprimento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetodoMegaHair")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("TipoCabelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("CatalogoItens");
                });

            modelBuilder.Entity("SimuladorMegaHair.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SimuladorMegaHair.Domain.Entities.Simulacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comprimento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoOriginalPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FotoResultadoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetodoMegaHair")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PromptUsado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderUtilizado")
                        .HasColumnType("text");

                    b.Property<long?>("TempoProcessamentoMs")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoCabelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ValorEstimado")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Simulacoes");
                });

            modelBuilder.Entity("SimuladorMegaHair.Domain.Entities.Simulacao", b =>
                {
                    b.HasOne("SimuladorMegaHair.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Simulacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SimuladorMegaHair.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Simulacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
